// Shared English copy (SPEC Appendix B, translated per OVERRIDES O1) and the glossary.
// Keys: `common.*`, `alerts.*` (§3.10), `errorKind.*` (§5.2.5). Plain everyday English, short
// sentences. Values are plain strings with {placeholders}; formatting happens before `t()`.

export const LOCALE = 'en-GB';

export const COPY = {
  // --- App chrome ------------------------------------------------------------------------------
  'common.appName': 'Dr.Filler · stats',
  'common.appShort': 'Dr.Filler',
  'common.skipToContent': 'Skip to content',
  'common.sections': 'Sections',
  'common.onThisPage': 'On this page',
  'common.signOut': 'Sign out',
  'common.legacy': 'Old version',
  'common.demo': 'Demo data',
  'common.settings': 'Settings',
  'common.menu': 'Menu',
  'common.filters': 'Filters',
  'common.refresh': 'Refresh',
  'common.done': 'Done',
  'common.refreshing': 'Refreshing data',
  'common.export': 'Export',
  'common.print': 'Print or save as PDF',
  'common.close': 'Close',
  'common.apply': 'Apply',
  'common.retry': 'Retry',
  'common.tryAgain': 'Try again',
  'common.loading': 'Loading…',
  'common.loadingApp': 'Loading Dr.Filler stats',
  'common.updated': 'Updated {time}',
  'common.stale': "Couldn't refresh — showing data from {time}.",
  'common.statsStart': 'Statistics start on {date}.',
  'common.tzWarning': 'Your browser is not on Vilnius time. Days are still counted in Vilnius time.',
  'common.placeholder.answer': 'The numbers for this page are on the way.',

  // --- Scope line and scope control (§3.2, §3.4) --------------------------------------------------
  'common.scopeLine': '{range} · compared with {compare} · {scopeText} · updated {time}',
  'common.scopeLine.noCompare': '{range} · {scopeText} · updated {time}',
  'common.scopeLine.prices': 'last 30 days, current model setup · all traffic, all accounts · updated {time}',
  'common.scope.label': 'Which accounts',
  'common.scope.all': 'All accounts',
  'common.scope.noInternal': 'Without my and test accounts ({n})',
  'common.scope.noInternalShort': 'Without my and test accounts',
  'common.scope.serviceChip': 'All traffic — all accounts',
  'common.scopeText.all': 'all accounts',
  'common.scopeText.noInternal': 'without my and test accounts ({n})',
  'common.scopeText.service': 'all traffic — all accounts',
  'common.scope.disabledHint': 'First mark your own and test accounts: Settings → “My and test accounts”.',
  'common.hiddenNote': 'Your own and test accounts are hidden ({n}). With them, costs would be {cost} and the result {result}.',
  'common.hiddenNote.noResult': 'Your own and test accounts are hidden ({n}). With them, costs would be {cost}.',

  // --- VAT (§3.5, OVERRIDES O4) --------------------------------------------------------------------
  'common.vatChip.off': "We don't pay VAT",
  'common.vatChip.on': 'We pay 21% VAT',
  'common.vatWord.off': 'no VAT',
  'common.vatWord.on': 'with VAT',

  // --- Period (§3.3) -------------------------------------------------------------------------------
  'common.period': 'Period',
  'common.period.choose': 'Choose period',
  'common.period.prev': 'Previous period',
  'common.period.next': 'Next period',
  'common.preset.last7': '7 days',
  'common.preset.last30': '30 days',
  'common.preset.month': 'Month',
  'common.preset.year': 'Year',
  'common.preset.allTime': 'All time',
  'common.preset.custom': 'Custom dates',
  'common.custom.title': 'Custom dates',
  'common.custom.selected': '(selected)',
  'common.custom.start': 'Start date',
  'common.custom.end': 'End date',
  'common.custom.inverted': 'The start must be on or before the end.',
  'common.custom.future': 'Dates cannot be after today.',
  'common.custom.beforeStart': 'Statistics start on {date}.',
  'common.compare.prevDays.one': 'the previous day',
  'common.compare.prevDays.other': 'the previous {n} days',
  'common.compare.monthPart': '{range}',
  'common.compare.month': '{month}',
  'common.compare.year': '{year}',
  'common.compare.range': '{range}',
  'common.caveat.model': '⚠ A different model was working in the period we compare with',
  'common.caveat.billing': '⚠ Recording used to be paid for differently',
  'common.caveat.hint': 'One of the two periods had a different setup ({era}). The difference may come from that, not from how doctors worked.',
  'common.noCompare': 'No earlier data',
  'common.noCompareBilling': 'nothing to compare with: recording used to be paid for differently',
  'common.nowTooShort': 'To convert to a month we need at least 7 days.',

  // --- Tiles, deltas, badges ------------------------------------------------------------------------
  'common.tile.noData': 'no data',
  'common.tile.loading': 'Loading',
  'common.tile.noValue': 'No value',
  'common.delta.up': 'Up {amount}{unit} {compare}',
  'common.delta.down': 'Down {amount}{unit} {compare}',
  'common.delta.flat': 'No change {compare}',
  'common.delta.unit.pct': ' percent',
  'common.delta.unit.pp': ' percentage points',
  'common.delta.unit.abs': '',
  'common.delta.unit.eur': ' euros',
  'common.badge.estimate': 'estimate',
  'common.badge.inferred': 'indirect',
  'common.badge.missing': 'no data',
  'common.badge.model': 'forecast',
  'common.hint.title': 'How we count',

  // --- Lists, tables, charts --------------------------------------------------------------------------
  'common.list.empty': 'Nothing to show for this period.',
  'common.list.showAll': 'Show all {n}',
  'common.list.showFewer': 'Show fewer',
  'common.list.shareOfTotal': '{share} of the total',
  'common.share': 'Share',
  'common.noData': 'No data',
  'common.table.caption': 'Data table',
  'common.showCalc': 'Show the math',
  'common.hideCalc': 'Hide the math',
  'common.showMore': 'More details',
  'common.showLess': 'Fewer details',
  'common.sortBy': 'Sort: {col}',
  'common.sortNone': 'default order',
  'common.sortLabel': 'Sort',
  'common.heat.time': 'Time',
  'common.heat.less': 'Less',
  'common.heat.more': 'More',
  'common.heat.noData': 'no data',
  'common.chart.loading': 'Loading…',
  'common.chart.error': 'Could not load this chart',
  'common.chart.errorHint': 'Use Refresh at the top of the page to try again.',
  'common.chart.asTable': 'View as table',
  'common.chart.asChart': 'View as chart',
  'common.chart.partial': 'in progress',
  'common.chart.partialTip': 'Still running — so far',
  'common.thin': 'Only {n} events so far — a chart needs {min}. Every event is listed below.',
  'common.thinChart': 'Too little data for a chart: {n}. See the list below.',
  'common.seriesEmpty': '{series}: none in this period',
  'common.notes.title': 'Data notes',

  // --- Empty states and errors ------------------------------------------------------------------------
  'common.empty.period': 'No data from {from} to {to}.',
  'common.empty.widen': 'Show 30 days',
  'common.empty.allTime': 'Show all time',
  'common.error.title': 'Could not load data',
  'common.error.network': 'No connection to the server. Check the internet and press “Retry”.',
  'common.error.timeout': 'The server took too long to answer. Press “Retry”.',
  'common.error.auth': "That key didn't work.",
  'common.error.apiOff': 'The stats are switched off on the server (no admin key in Railway).',
  'common.error.server': 'The server answered with an error. Press “Retry”.',
  'common.error.limited': 'The history is too big to load at once — showing the last 90 days.',
  'common.error.schema': 'The server sent data in a shape this page does not know. Try again later.',
  'common.error.conflict': 'The server refused the change.',
  'common.error.saveFailed': 'Could not save. Your changes are still in the form.',
  'common.newVersion.title': 'A new version is out',
  'common.newVersion.body': 'The stats site was updated while this tab was open. Reload to get the new version.',
  'common.reload': 'Reload',
  'common.pageError.title': 'This page could not be shown',
  'common.pageError.body': 'Something went wrong while preparing these numbers. The other pages still work.',
  'common.rootError.title': 'Something went wrong',
  'common.rootError.body': 'The stats could not start. Try a hard refresh (Cmd+Shift+R).',

  // --- Sources (§3.2 SourceBanner) ------------------------------------------------------------------
  'common.source.revenueOff': 'Stripe is not connected — income is shown indirectly, from credit balances.',
  'common.source.revenueError': "Stripe didn't answer — income is not shown right now.",
  'common.source.stripeTest': 'Stripe is connected in test mode: payments do not count as income.',
  'common.source.sonioxOff': 'Soniox is not connected to the stats.',
  'common.source.sonioxError': "Soniox didn't answer — its own usage numbers are missing.",
  'common.source.configOff': 'Server settings were not received — using the built-in price table from {date}.',
  'common.source.costsError': 'Invoices entered by hand could not be loaded.',
  'common.source.settingsError': 'Saved settings could not be loaded — using the defaults.',

  // --- Export and print ----------------------------------------------------------------------------------
  'common.export.csvTitle': 'CSV from this page',
  'common.export.failed': 'Could not export',
  'common.export.done': 'File downloaded',
  'common.export.printTip': 'For a clean PDF, untick “Headers and footers” in the print dialog.',
  'common.print.report': 'Dr.Filler stats — {section}',
  'common.print.compared': 'Compared with {range}',
  'common.print.generated': 'Made on {date}, {time}',
  'common.print.privacy': 'No patient data. Doctors are shown by email.',
  'common.print.preparing': 'Preparing the report…',

  // --- Right now strip (§3.2) ------------------------------------------------------------------------------
  'common.live.lead': 'Right now',
  'common.live.failed': "Couldn't refresh",
  'common.live.refresh': 'Refresh live numbers',
  'common.live.aria': 'Right now',

  // --- Sign in (§5.3.9 KeyGate) -------------------------------------------------------------------------
  'common.key.title': 'Sign in to the stats',
  'common.key.label': 'Access key',
  'common.key.remember': 'Remember on this device',
  'common.key.submit': 'Sign in',
  'common.key.change': 'Change key',
  'common.key.checking': 'Checking the key…',
  'common.key.hint': 'The same admin key as in the old version.',

  // --- Planning and projection (§3.8, ScaleProjection) ------------------------------------------------------
  'common.plan.chips': '{visits} visits · {scenario} · {packLabel} · {vatWord} · {free}',
  'common.plan.packSingle': 'pack {pack}',
  'common.plan.packMix': 'packs as planned',
  'common.plan.edit': 'Change',
  'common.plan.chip.visits': '{n} visits',
  'common.plan.chip.free': '{share} of work is free',
  'common.plan.chip.noFree': 'no free use',
  'common.warning.FEW_FORMS_ASSUMED': 'Fewer than 20 forms with the current model setup in the last 30 days — the price of a form uses the assumed size from Settings.',
  'common.warning.MEASURED_FALLBACK': 'Fewer than 20 recordings in the last 30 days — “as now” uses your plan instead.',
  'common.warning.SONIOX_STREAM_LIMIT': 'At {doctors} doctors, more conversations would run at once than Soniox allows.',
  'common.warning.DASHBOARD_ROWS': 'At {doctors} doctors, the stats history would grow too big for one load within a year.',
  'common.scenario.plan': 'my plan',
  'common.scenario.typed': 'typing only',
  'common.scenario.dictation1': '1 min dictation',
  'common.scenario.live15': '15 min conversation',
  'common.scenario.live25': '25 min conversation',
  'common.scenario.measured': 'as now',
  'common.scenario.live': '{min} min conversation',
  'common.scenario.dictation': '{min} min dictation',
  'common.scenario.mixed': '{min} min conversation in {share} of visits',
  'common.col.now': 'Now, per month',
  'common.col.nowSub': 'converted from {range}',
  'common.col.visit': '1 visit',
  'common.col.doctor': 'Per doctor',
  'common.col.doctorMonth': 'Doctor per month',
  'common.col.scale': '{n} doctors',
  'common.row.income': 'Income',
  'common.row.cost': 'Costs',
  'common.row.result': 'Result',
  'common.row.left': 'Kept, %',
  'common.row.paid': 'Paid by doctors',
  'common.projection.card': '{col}: income {income}, costs {cost}, result {result}',
  'common.billingRule':
    'How doctors pay: 1 credit for every form (“Generuoti”) + 1 credit for every full 10 minutes of recording. Dictation and conversation share one counter, and leftover minutes carry over. A credit costs the doctor 3–5 cents: packs of 250 / 600 / 1500 for €12.50 / €24 / €45. This is how it works since 23 Sep 2026; before that, recording was almost always free.',

  // --- Account classes (§5.3.7 Doctor) -------------------------------------------------------------------------
  'common.class.internal': 'My and test',
  'common.class.paid': 'Paying',
  'common.class.bought_inferred': 'Paying (by balance)',
  'common.class.bought_unverified': 'Purchase not found',
  'common.class.legacy': 'Gift (old plan)',
  'common.class.gifted': 'Gift',
  'common.class.free': 'Free 15',
  'common.class.no_credits_doc': 'No balance',
  'common.class.deleted': 'Deleted',
  'common.class.unknown': 'Unknown',
  'common.displayClass.internal': 'My and test',
  'common.displayClass.paid': 'Paying',
  'common.displayClass.gifted': 'Gift',
  'common.displayClass.free': 'Free 15',
  'common.displayClass.other': 'Other',
  'common.doctor.name': 'Doctor {no}',
  'common.doctor.deleted': 'Deleted account',
  'common.doctor.noAccount': 'No account',

  // The period inside a sentence ("We made €12 {period}")
  'common.period.lastDays': 'over the last {n} days',
  'common.period.month': 'in {month}',
  'common.period.monthSoFar': 'in {month} so far',
  'common.period.year': 'in {year}',
  'common.period.yearSoFar': 'in {year} so far',
  'common.period.allTime': 'since {date}',
  'common.period.range': 'over {range}',
  'common.doctor.markMine': 'Mark as mine',
  'common.doctor.lockedByServer': 'set on the server',

  // --- Not recorded footnote (§3.9) --------------------------------------------------------------------------
  'common.notRecorded.before':
    'Not recorded yet: errors and refusals, credit refunds, recording charges (we count them from minutes), whether and why the backup model answered, and Google’s discount for repeated text. Only successful requests are visible.',
  'common.notRecorded.after':
    'Since {date} we record failures, refusals, recording charges and whether the backup model answered. Numbers before that date are an estimate.',
  'common.note.openaiShareAssumed': 'The forecast assumes no OpenAI backup dictations: there are fewer than 20 dictations through Soniox so far.',

  // --- Alerts (§3.10) -------------------------------------------------------------------------------------------
  'common.alerts.title': 'Needs attention',
  'alerts.notCredited':
    '{n} {payments} did not turn into credits. Add the credits by hand, then check Stripe → Developers → Webhooks (the link from Stripe to our server).',
  'alerts.stripeTestMode': 'Stripe is connected in test mode: payments do not count as income.',
  'alerts.fallbackToday': 'The main model is slow today: the backup model answered {n} times (usually 0–1). Doctors wait about 30 s.',
  'alerts.slowToday': '{pct} of forms took longer than 15 s today — doctors wait longer than usual. Most likely Google is slow; it usually passes on its own.',
  'alerts.failuresHour': '{n} requests ended with an error in the last hour — doctors saw an error instead of a result.',
  'alerts.liveNearLimit': '{n} of {limit} possible Soniox conversations are running now. The next one may get “busy”.',
  'alerts.silence': 'Not a single form since the morning, although it is a working day. Check that the service works.',
  'alerts.anamCap': 'Medical history summaries: {x} of the {cap} daily limit is spent. When the limit runs out, new summaries are refused until midnight.',
  'alerts.openaiDictation': '{n} dictations went to the backup OpenAI today — Soniox may not have answered. This costs 1.8 times more.',
  'alerts.lifecycleSoon': 'In {d} days Google will switch off {model}.',
  'alerts.revenueDown': "Stripe didn't answer — income is not shown right now.",
  'alerts.pricesStale': 'Prices were checked on {date}. Time to compare them with the vendors’ websites.',

  // --- Error kinds (§5.2.5) -----------------------------------------------------------------------------------
  'errorKind.timeout': 'the model did not answer in time',
  'errorKind.upstream_429': 'Google is overloaded (429)',
  'errorKind.upstream_5xx': 'Google error (5xx)',
  'errorKind.upstream_4xx': 'Google refused the request (4xx)',
  'errorKind.model_not_found': 'the model is gone (404)',
  'errorKind.invalid_json': 'broken answer from the model',
  'errorKind.max_tokens': 'answer cut off by length',
  'errorKind.repetition': 'the model got stuck in a loop',
  'errorKind.internal': 'server error',
  'errorKind.credit_store': 'credit bookkeeping error',
  'errorKind.service_off': 'service switched off',
  'errorKind.transcription_failed': 'transcription failed',
  'errorKind.soniox_busy': 'Soniox is busy',
  'errorKind.unavailable': 'recording unavailable',
  'errorKind.live_off': 'live recording switched off',
  'errorKind.no_credits': 'no credits',
  'errorKind.daily_cap': 'daily conversation limit',
  'errorKind.too_many_open': 'too many open conversations',
  'errorKind.session_used': 'conversation already closed',
  'errorKind.cap': 'medical history limit',
  'errorKind.queue_full': 'medical history queue is full',
  'errorKind.client_gone': 'the doctor closed the window',
  'errorKind.invalid_audio': 'bad recording file',
  'errorKind.unknown': 'other error',

  // --- Friendly names (§3.11, OVERRIDES O1) --------------------------------------------------------------------
  'common.model.gemini-3-flash-preview': 'Gemini 3 Flash (trial version)',
  'common.model.gemini-3.5-flash-lite': 'Gemini 3.5 Flash-Lite',
  'common.model.gemini-3.5-flash': 'Gemini 3.5 Flash',
  'common.model.gemini-3.6-flash': 'Gemini 3.6 Flash',
  'common.model.gemini-3.7-flash': 'Gemini 3.7 Flash',
  'common.model.gemini-3.8-flash': 'Gemini 3.8 Flash',
  'common.model.gemini-3.1-flash-lite': 'Gemini 3.1 Flash-Lite',
  'common.model.gemini-3.1-pro-preview': 'Gemini 3.1 Pro (trial version)',
  'common.model.gemini-2.5-flash': 'Gemini 2.5 Flash (old)',
  'common.model.gemini-2.5-flash-lite': 'Gemini 2.5 Flash-Lite (old)',
  'common.model.gemini-2.5-pro': 'Gemini 2.5 Pro (old)',
  'common.model.soniox:stt-async-v5': 'Soniox, audio file',
  'common.model.soniox-rt:stt-rt-v5': 'Soniox, live conversation',
  'common.model.gpt-4o-mini-transcribe': 'OpenAI mini-transcribe',
  'common.model.mixed': 'several models (test day)',
  'common.endpoint.direct': 'Google API (direct)',
  'common.endpoint.global': 'Google Cloud, any country',
  'common.endpoint.eu': 'Google Cloud, EU only',
  'common.endpoint.europe-west1': 'Google Cloud, Belgium',
  'common.endpoint.europe-west2': 'Google Cloud, London',
  'common.endpoint.europe-west3': 'Google Cloud, Frankfurt',
  'common.endpoint.europe-west4': 'Google Cloud, Netherlands',
  'common.endpoint.other': 'Google Cloud, {location}',
  'common.thinking.low': 'thinks a little',
  'common.thinking.minimal': 'barely thinks',
  'common.thinking.budget0': 'no thinking',
  'common.thinking.other': 'thinking: {level}',
  'common.status.preview': 'trial version – may be removed',
  'common.status.stable': 'stable',
  'common.status.short-term': 'short-term – 45 days’ notice',
  'common.status.legacy-limited': 'old, limited access',

  // --- Unit words (plural forms by Intl.PluralRules category) -------------------------------------------------
  'common.unit.payment.one': 'payment',
  'common.unit.payment.other': 'payments',
  'common.unit.credit.one': 'credit',
  'common.unit.credit.other': 'credits',
  'common.unit.doctor.one': 'doctor',
  'common.unit.doctor.other': 'doctors',
  'common.unit.conversation.one': 'conversation',
  'common.unit.conversation.other': 'conversations',
  'common.unit.form.one': 'form',
  'common.unit.form.other': 'forms',
  'common.unit.tokens': 'tokens',
  'common.unit.page.one': 'page',
  'common.unit.page.other': 'pages',
  'common.unit.minute.one': 'minute',
  'common.unit.minute.other': 'minutes',
  'common.unit.day.one': 'day',
  'common.unit.day.other': 'days',
  'common.unit.visit.one': 'visit',
  'common.unit.visit.other': 'visits',
  'common.unit.request.one': 'request',
  'common.unit.request.other': 'requests',
  'common.unit.event.one': 'event',
  'common.unit.event.other': 'events',
  'common.unit.cent': '¢',
  'common.unit.sec': 's',
  'common.unit.ms': 'ms',
  'common.unit.min': 'min',
  'common.unit.hour': 'h',
  'common.unit.pp.one': 'point',
  'common.unit.pp.other': 'points',
  'common.unit.thousand': 'k',
  'common.unit.million': 'M',
  'common.unit.of': '{n} of {total}',
  'common.unit.shareOf': '{share} ({n} of {total})',
  'common.unit.lessThan': '<{x}',
  'common.unit.approx': '≈ {x}',
  'common.unit.ago.now': 'just now',
  'common.unit.ago.min': '{n} min ago',
  'common.unit.ago.hour': '{n} h ago',
  'common.unit.ago.day': '{n} days ago',
  'common.months.short': 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
  'common.months.long': 'January|February|March|April|May|June|July|August|September|October|November|December',
  'common.weekdays.short': 'Mon|Tue|Wed|Thu|Fri|Sat|Sun',
  'common.fmt.eurUsd': '{eur} = {usd} at list price',
  'common.fmt.weekOf': 'Week of {date}',
};

/**
 * Glossary and shared hints (`{ short, long?, template? }`). `common.term.*` are exempt from the
 * ban list: they are where a technical word is explained once.
 */
export const DEFS = {
  'common.term.credit': {
    short: 'A credit is what the doctor pays with: 1 for a form and 1 for every 10 minutes of recording.',
    long: 'In the extension it is called “konsultacija”. A credit costs the doctor 3–5 cents, depending on the pack. Since 23 Sep 2026 recording is paid by a minute counter (dictation and conversation together, leftovers carry over); before that it was paid per visit.',
  },
  'common.term.token': {
    short: 'A token is a small piece of text, about 3–4 letters. Models count and charge in tokens.',
    long: 'The request is what we send to the model; the answer is what it writes. Answer tokens cost 6 times more. One page of text (1,800 characters) is about 660 tokens.',
  },
  'common.term.listPrice': {
    short: 'Costs at list price — at the prices on the vendors’ websites. This is an upper limit, not the invoice.',
    long: 'Right now Google’s promo credits cover most of its invoice. When they run out, the payment will get close to this number. Real invoices can be entered on the Costs page.',
  },
  'common.term.estimate': {
    short: 'Estimate — the number is worked out indirectly; it is not recorded directly.',
    long: 'The (i) of the tile says why. When the server starts recording this field, the label goes away.',
  },
  'common.term.inferred': {
    short: 'Indirect — the number is guessed from other data, for example purchases from credit balances.',
    long: 'When Stripe is connected, the label goes away.',
  },
  'common.term.model': {
    short: 'Forecast — a “what if” calculation from the assumptions in Settings, not a promise.',
  },
  'common.term.left': {
    short: 'Kept, % — the part of income we keep after all costs: (income − costs) ÷ income.',
    long: 'This is not a markup. The same formula is used everywhere in the stats.',
  },
  'common.term.mainModel': {
    short: 'The main model writes the forms on a normal day.',
    long: 'Right now it is a trial version: Google may replace it.',
  },
  'common.term.fallbackModel': {
    short: 'The backup model answers when the main one is silent for 25 s or Google returns an error.',
    long: 'The doctor still gets the form, but usually waits 27–30 s.',
  },
  'common.term.setupHistory': {
    short: 'Setup history — which model and which way of paying were used on which dates.',
    long: 'A change of setup explains jumps on the charts. The whole history is in Settings.',
  },
  'common.term.median': {
    short: 'Median — the middle of the list: half of the values are smaller, half are bigger.',
    long: 'Rare, very large values do not spoil it.',
  },
  'common.term.p90': {
    short: '“9 of 10” — 9 values out of 10 are below this number.',
    long: 'It shows the bad cases that the median hides.',
  },
  'common.term.internal': {
    short: 'My and test accounts — your own accounts and test accounts.',
    long: 'You can hide them with the “Without my and test accounts” switch. Speed and failures always count all traffic.',
  },
  'common.term.vat': {
    short: 'VAT — the 21% tax inside the pack price. We count it only if the company pays it.',
    long: 'Change it in Settings.',
  },
  'common.term.webhook': {
    short: 'Webhook — the message Stripe sends to our server after a payment.',
    long: 'This is what gives the doctor the credits.',
  },
  'common.term.promoCredits': {
    short: 'Promo credits — free money from Google that currently pays the invoice.',
    long: 'When they run out, the same amount of work will cost the list price.',
  },
  'common.term.prompt': {
    short: 'Our instructions to the model (the prompt) — the text with the rules for filling in the form.',
    long: 'It is the same in every request and takes up most of the request.',
  },
  'common.term.pp': {
    short: 'Points (percentage points): the plain difference between two percentages. From 2% to 5% is +3 points.',
  },
  'common.term.cache': {
    short: 'Cache — Google’s discount for repeated text: Google remembers the same start of a request for a few minutes and charges 10% of the price for it.',
    long: 'We count costs at the full list price and show the discount separately.',
  },
  'common.term.vertex': {
    short: 'Vertex — the same Gemini, but through Google Cloud, where you can choose the country of the servers.',
  },
  'common.term.preview': {
    short: 'Trial version of a model: Google may remove it at short notice.',
  },
  'common.term.scale': {
    short: 'Forecast for the plan: {visits} visits per doctor per month.',
    template: 'Forecast for the plan: {visits} visits per doctor per month.',
    long: 'Prices come from real data of the last 30 days (current model setup); the amount of work comes from Settings. This is a “what if” calculation, not a promise.',
  },
  'common.scope.service': {
    short: 'Speed, failures and load count all accounts: your own account is real load too.',
  },
  'common.fx': {
    short: 'We convert dollars at the ECB rate.',
    template: 'We convert dollars at the ECB rate: $1 = €{fx} on {date}.',
    long: 'Vendors bill in dollars; Stripe pays out in euros.',
  },
  'common.liveNow': {
    short: 'Live numbers for today, all accounts. They refresh every minute and do not follow the period.',
  },
};

/**
 * Rules for `copy.test.mjs`: the fixed vocabulary (§3.11) and the ban list (OVERRIDES O1), applied to
 * every COPY value and every DEFS.short except `common.term.*`.
 */
export const RULES = {
  vocabulary: ['Paid by doctors', 'Income', 'Costs', 'Result', 'Kept, %', 'Form', 'Visit', 'Request', 'Credit'],
  banned: [
    /\bmargin\b/i,
    /unit economics/i,
    /\bwebhook\b/i,
    /\bcache\b/i,
    /\bendpoint\b/i,
    /\bvs\.?\b/i,
    /\bp50\b|\bp90\b/i,
    /\blatency\b/i,
    /\bprompt\b/i,
    /\bKPI\b/,
    /\bpreview\b/i,
    /\bEEA\b/,
  ],
};
