// Copy of the Models page (§4.6, translated per OVERRIDES O1). Every key starts with 'models.'.
// COPY = labels, answers, empty states, table headers, takeaways; DEFS = { short, long?, template? }
// for the (i) hints (hintKey 'models.<key>'). Plain everyday English, short sentences.

export const COPY = {
  'models.title': 'Models',
  'models.question': 'Which model answers, and is it fast and without failures?',

  // --- Answer (§4.6) ---------------------------------------------------------------------------
  'models.answer.now': 'Forms are written by {main}, {where}. The backup model, {fallback}, stepped in for {n} of {N} forms.',
  'models.answer.nowSince': 'Forms are written by {main}, {where}. The backup model, {fallback}, stepped in for {n} of {N} forms since {since} (when it was added).',
  'models.answer.nowSolo': 'Forms are written by {main}, {where}.',
  'models.answer.speed': 'A form usually arrives in {usual}, and 9 out of 10 come faster than {nineOfTen}. Longer than 15 s: {over15} of {forms}.',
  'models.answer.noForms': 'No forms in this period.',
  'models.answer.risk404':
    'Risk: the main model is a trial version. If Google removes it, the backup will not switch on by itself, and doctors will see an error.',
  'models.answer.failures': 'Service failures: {n} of {N} requests.',
  'models.answer.failuresOff': 'Errors are not recorded yet: only successful requests are visible.',
  'models.where.direct': 'directly from Google',
  'models.where.cloud': 'through {place}',
  'models.word.yes': 'yes',
  'models.word.no': 'no',
  'models.provider.soniox': 'Soniox',
  'models.provider.openai': 'OpenAI',
  'models.weekdays.long': 'Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday',

  // --- Right now strip ---------------------------------------------------------------------------
  'models.live.lastForm': 'last form',
  'models.live.forms': 'forms today',
  'models.live.fallback': 'backup model today',
  'models.live.failures': 'failures in the last hour',
  'models.live.conversations': 'conversations running',
  'models.live.ofLimit': '{n} of {limit}',

  // --- Sections --------------------------------------------------------------------------------------
  'models.nav.now': 'Now',
  'models.nav.speed': 'Speed',
  'models.nav.fallback': 'Backup',
  'models.nav.failures': 'Failures',
  'models.nav.load': 'Load',
  'models.nav.risks': 'Risks',
  'models.section.now': 'Now',
  'models.section.speed': 'Speed',
  'models.section.speedSub': 'How long doctors wait for a form. All accounts.',
  'models.section.fallback': 'Backup model',
  'models.section.fallbackSub': 'Forms the backup model wrote when the main one did not answer.',
  'models.section.failures': 'Failures',
  'models.section.failuresSub': 'Requests that ended with an error or a refusal. All accounts.',
  'models.section.load': 'Load',
  'models.section.loadSub': 'When doctors make forms. All accounts.',
  'models.section.risks': 'Risks and dates',
  'models.section.risksSub': 'What may break or cost more, and when.',
  'models.empty.title': 'No forms in this period',
  'models.empty.hint': 'Choose a longer period to see speed and the backup model.',

  // --- Now card ----------------------------------------------------------------------------------------
  'models.now.title': 'Working now',
  'models.now.main': 'Main: {main} — {where}. Servers in the EU: {eu}.',
  'models.now.fallback': 'Backup: {fallback} — takes over if the main model is silent for {timeout} or Google returns an error.',
  'models.now.fallback404': 'Backup: {fallback} — takes over if the main model is silent for {timeout}, Google returns an error, or the model is gone.',
  'models.now.noFallback': 'No backup model is set: if the main model fails, doctors see an error.',
  'models.now.preview': 'The main model is a trial version. It has no shutdown date; Google may remove it at short notice.',
  'models.now.fallbackStable': 'The backup model stays available at least until {date}.',
  'models.now.transcription': 'Transcription: {provider} (audio files and live conversations), backup — {fallbackProvider}.',
  'models.now.transcriptionSolo': 'Transcription: {provider} (audio files and live conversations), no backup.',
  'models.now.server': 'The server was updated {ago} (build {build}).',

  // --- Speed ---------------------------------------------------------------------------------------------
  'models.tile.p50': 'Usual answer time',
  'models.tile.p90': '9 of 10 are faster than',
  'models.tile.over15': 'Longer than 15 seconds',
  'models.tile.over15Sub': 'of them longer than 25 s: {n}',
  'models.tile.fallback': 'Backup stepped in',
  'models.tile.fallbackSub': 'doctors usually waited {wait}',
  'models.tile.fallbackNone': 'not needed in this period',
  'models.waitHist.title': 'How long doctors waited',
  'models.waitHist.range': '{from}–{to} s',
  'models.waitHist.over': 'over {from} s',
  'models.waitHist.fallbackMark': 'backup',
  'models.waitHist.unit': 'forms',
  'models.waitHist.ofFallback': 'of them, backup model: {n}',
  'models.waitHist.col.wait': 'Wait',
  'models.waitHist.col.forms': 'Forms',
  'models.waitHist.col.fallback': 'Of them, backup model',
  'models.takeaway.waitHist': 'A form is usually ready in {usual}. Long waits (over 25 s): {n}, almost all because of the backup model.',
  'models.latency.title': 'Answer time by month',
  'models.latency.p50': 'usual',
  'models.latency.p90': '9 of 10',
  'models.latency.ref15': 'slow',
  'models.latency.refTimeout': 'waiting for the backup',
  'models.latency.bands': 'Grey band: {list}.',
  'models.latency.col.month': 'Month',
  'models.latency.col.forms': 'Forms',
  'models.slow.show': 'Show the math: slow answers ({n})',
  'models.slow.title': 'Slow answers (over 15 s)',
  'models.slow.capped': 'Showing the newest {n} of {total}.',
  'models.slow.empty': 'No form took longer than 15 s in this period.',

  // --- Causes and reasons --------------------------------------------------------------------------------
  'models.cause.fallbackReason': 'backup model: {reason}',
  'models.cause.fallbackSilent': 'the main model did not answer in 25 s — the backup answered',
  'models.cause.fallbackError': 'the main model returned an error — the backup answered',
  'models.cause.era': 'a different setup on those days: {era}',
  'models.cause.bigRequest': 'a very big request',
  'models.cause.longAnswer': 'a very long answer',
  'models.cause.slowModel': 'the model wrote slowly (Google)',
  'models.cause.unclear': 'unclear',
  'models.era.vertexEu': 'Google Cloud in the EU',
  'models.era.testDay': 'model test day',
  'models.era.test': 'short test',
  'models.reason.timeout': 'the main model was silent too long',
  'models.reason.http_429': 'Google was overloaded (429)',
  'models.reason.http_500': 'Google error (500)',
  'models.reason.http_503': 'Google error (503)',
  'models.reason.http_504': 'Google error (504)',
  'models.reason.overloaded': 'Google was overloaded',
  'models.reason.model_not_found': 'the main model is gone (404)',
  'models.reason.unknown': 'another error',
  'models.fbReason.silent': 'the main model was silent',
  'models.fbReason.error': 'a quick error from Google',

  // --- Table columns ---------------------------------------------------------------------------------------
  'models.col.when': 'When',
  'models.col.doctor': 'Doctor',
  'models.col.model': 'Model',
  'models.col.waited': 'Waited',
  'models.col.requestPages': 'Request, pages',
  'models.col.answerTokens': 'Answer, tokens',
  'models.col.tokensPerSec': 'Wrote, tokens/s',
  'models.col.cause': 'Likely cause',
  'models.col.reason': 'Reason',
  'models.col.cost': 'Cost',
  'models.col.from': 'From',
  'models.col.to': 'To',
  'models.col.main': 'Main',
  'models.col.fallback': 'Backup',
  'models.col.where': 'Where',
  'models.col.note': 'Note',
  'models.col.role': 'Role',
  'models.col.span': 'When',
  'models.col.forms': 'Forms',
  'models.col.usual': 'Usual',
  'models.col.p90': '9 of 10',
  'models.col.over15': 'Over 15 s',
  'models.col.formPrice': 'Price of a form',
  'models.col.perDoctor': 'Forms only, per doctor per month',
  'models.col.status': 'Status at Google',
  'models.col.shutdown': 'Shutdown',
  'models.col.activity': 'What they were doing',
  'models.col.what': 'What happened',
  'models.col.code': 'Code',
  'models.col.refunded': 'Credit returned',

  // --- Backup section ----------------------------------------------------------------------------------------
  'models.fallbackEvents.title': 'When the backup model stepped in',
  'models.fallbackEvents.empty': 'The backup model was not needed in this period.',
  'models.fallbackEvents.before': 'There was no backup model then — it was switched on on 1 Sep 2026.',
  'models.fallbackEvents.capped': 'Showing the newest {n} of {total}.',
  'models.eras.title': 'Setup history',
  'models.eras.now': 'now',
  'models.eraNote.current': 'current setup',
  'models.eraNote.test': 'a short test',
  'models.eraNote.vertexEu': 'a week on Google Cloud in the EU',
  'models.eraNote.testDay': 'a day of model tests',
  'models.table.show': 'Show the math: all models of the period ({n})',
  'models.table.title': 'Models: speed and price',
  'models.role.main': 'main',
  'models.role.fallback': 'backup',
  'models.role.switch': 'test or manual switch',

  // --- Failures section ---------------------------------------------------------------------------------------
  'models.failures.offTitle': 'Failures are not recorded yet',
  'models.failures.offHint':
    'When a request fails, no line is written to the log, and the credit is returned. So this stays empty even if doctors saw an error.',
  'models.proxies.title': 'What we can already see',
  'models.proxy.fallback': 'Backup model stepped in',
  'models.proxy.over25': 'Longer than 25 s',
  'models.proxy.maxTokens': 'Summaries cut short',
  'models.proxy.emptyDictation': 'Empty dictation transcript',
  'models.proxy.reconnects': 'Reconnects in conversations',
  'models.tile.serviceFailures': 'Service failures',
  'models.tile.serviceFailuresSub': '{rate} of requests',
  'models.tile.serviceFailuresSubSince': '{rate} of requests since {since}',
  'models.tile.refusals': 'Refusals',
  'models.tile.refusalsSub': 'most often: {kind}',
  'models.tile.refusalsNone': 'none in this period',
  'models.failures.show': 'Show the math: what broke and when ({n})',
  'models.failuresByKind.title': 'What broke',
  'models.failuresByKind.empty': 'Nothing broke in this period.',
  'models.refusalsByKind.title': 'Why the server said no',
  'models.refusalsByKind.empty': 'No refusals in this period.',
  'models.failuresChart.title': 'Failures over time',
  'models.failuresChart.unit': 'failures',
  'models.failuresRecent.title': 'Latest failures and refusals',
  'models.failuresRecent.empty': 'No failures or refusals in this period.',
  'models.activity.form': 'form',
  'models.activity.dictation': 'dictation',
  'models.activity.live': 'conversation',
  'models.activity.anamnesis': 'history summary',
  'models.activity.other': 'other',
  'models.group.refusal': 'refusal',

  // --- Load section --------------------------------------------------------------------------------------------
  'models.heatmap.title': 'When the load comes',
  'models.heatmap.few': 'Too little data for the map — choose 30 days or more.',
  'models.heatmap.fewHint': 'The map needs at least {min} forms; this period has {n}.',
  'models.heatmap.legend': 'forms per hour',
  'models.heatmap.cell': '{day}, {hour}:00: {n} forms',
  'models.heatmap.weekend': 'Sat–Sun',
  'models.takeaway.heatmap': 'The busiest hour is {day} at {hour}:00: {share} of that day’s forms.',

  // --- Risks section ------------------------------------------------------------------------------------------
  'models.risks.title': 'What may break',
  'models.col.risk': 'What',
  'models.col.riskStatus': 'Status',
  'models.col.date': 'Date',
  'models.col.daysLeft': 'Days left',
  'models.col.happens': 'What will happen',
  'models.col.todo': 'What to do',
  'models.risk.what.main': 'Main model: {model}',
  'models.risk.what.sonioxLimit': 'Soniox limit, {limit} conversations',
  'models.risk.what.sonioxEu': 'Soniox: servers in the EU and a data processing agreement',
  'models.risk.what.prepay': 'Gemini prepayment (AI Studio)',
  'models.risk.what.promo': 'Google promo credits',
  'models.risk.what.openai': 'Backup transcription: {model}',
  'models.risk.what.fallback': 'Backup model: {model}',
  'models.risk.what.legacy': 'Gemini 2.5 through Google Cloud',
  'models.risk.status.previewOpen': 'trial version, no date — if Google removes it, the backup will not switch on',
  'models.risk.status.previewSafe': 'trial version, no date — protected: the backup will switch on',
  'models.risk.status.plain': '{status}',
  'models.risk.status.limit': 'limit',
  'models.risk.status.check': 'to check',
  'models.risk.status.manual': 'check by hand',
  'models.risk.status.runOut': 'will run out',
  'models.risk.status.shutdown': 'will be switched off',
  'models.risk.status.noDate': 'no shutdown date',
  'models.risk.status.priceRise': 'price × {factor}',
  'models.risk.status.closing': 'closing',
  'models.risk.date.notAnnounced': 'not announced',
  'models.risk.date.notBefore': 'not before {date}',
  'models.risk.date.doctors': 'on average at {meanDoctors} doctors; with no refusals at {limitDoctors}',
  'models.risk.date.noLive': 'no live conversations in the plan',
  'models.risk.happens.mainGone': 'Google answers “model not found” → forms fail until the backup is switched on',
  'models.risk.happens.mainGoneSafe': 'Google answers “model not found” → the backup writes the forms',
  'models.risk.happens.busy': 'conversation number {next} gets “busy”',
  'models.risk.happens.gdpr': 'a GDPR question (EU data protection law) once real patients are recorded',
  'models.risk.happens.prepayZero': 'balance 0 → forms stop working (happened on 4 Sep)',
  'models.risk.happens.invoiceGrows': 'the invoice grows to the list price',
  'models.risk.happens.backupTranscriptionStops': 'the backup transcription stops working',
  'models.risk.happens.oursCostMore': 'our forms cost {factor} times more',
  'models.risk.happens.onlyIfSwitch': 'matters only if we switch to them',
  'models.risk.happens.formsFail': 'forms fail',
  'models.risk.happens.noEffect': 'does not affect our work',
  'models.risk.todo.keepReady': 'Keep {ready} ready',
  'models.risk.todo.askLimit': 'Ask Soniox to raise the limit early',
  'models.risk.todo.askSoniox': 'Ask Soniox for an EU region and a data processing agreement (DPA)',
  'models.risk.todo.watchBalance': 'Watch the balance in AI Studio; the API does not show it',
  'models.risk.todo.seeCosts': 'See Costs → “List price and invoice”',
  'models.risk.todo.changeInRailway': 'Change the model in Railway',
  'models.risk.todo.seePrices': 'Take it into account on the Prices page',

  // --- Notes ----------------------------------------------------------------------------------------------------
  'models.note.vertexEra':
    'This period includes the week of 26 Aug – 1 Sep, when the main model was Gemini 3.7 Flash through Google Cloud in the EU. So speed and price are worse than usual.',
  'models.note.testDay': '1 Sep was a model test day: its forms count neither as the main nor as the backup model.',
};

export const DEFS = {
  'models.p50': {
    short: 'The median: half of the forms came faster. This is the model’s working time, without the network to the doctor.',
    long: 'The median is the middle of the list; rare, very long answers do not spoil it. In September the median grew from about 4 to 6 s: the answers got longer, the model did not get slower.',
  },
  'models.p90': {
    short: '9 forms out of 10 came faster than this.',
    long: 'It shows the bad minutes. If this number grows and the median does not, Google is sometimes slow.',
  },
  'models.over15': {
    short: 'How many forms took longer than 15 s. A doctor notices a wait like that.',
    template: 'How many forms took longer than 15 s: {share} of all forms. A doctor notices a wait like that.',
    long: 'Longer than 25 s means the main model did not answer in time and we waited for the backup.',
  },
  'models.fallback': {
    short: 'How many forms the backup model wrote, out of the forms since 2 Sep (it has been on all the time since then).',
    template: 'How many forms the backup model wrote, out of the forms since 2 Sep (it has been on all the time since then): {share}.',
    long: 'Until the server marks the backup model itself, we recognise it by the model name and the setup dates (an estimate). The test day, 1 Sep, does not count. If the main model returned an error at once, the form arrives in about 6 s; if it was silent, in 27–30 s.',
  },
  'models.tokensPerSec': {
    short: 'How many tokens a second the model wrote.',
    long: 'It helps tell “Google is slow” from “the answer got longer”. An estimate: the time also includes the model reading the request.',
  },
  'models.waitHist': {
    short: 'How many forms came in 0–3 s, 3–5 s and so on.',
    long: 'The hump at 25–30 s is the forms that went through the backup model.',
  },
  'models.latency': {
    short: 'Usual and “9 of 10” by month. The 15 s and 25 s lines mean “slow” and “waiting for the main model”.',
    long: 'Grey bands are special periods (for example, Google Cloud in the EU, 26 Aug – 1 Sep). Months with fewer than 5 forms are not drawn.',
  },
  'models.slow': {
    short: 'Every form over 15 s and its likely cause.',
    long: 'We guess the cause by rules: the backup model, a different setup on those days, a very big request, a very long answer, a slow model. It is a hint, not a diagnosis.',
  },
  'models.fallbackEvents': {
    short: 'Every case: when, how long the doctor waited and why.',
  },
  'models.eras': {
    short: 'Which model was the main one and which the backup, on which dates.',
    long: 'A change of setup explains jumps on the charts.',
  },
  'models.table': {
    short: 'Every model that wrote forms: how many, how fast and at what price.',
    long: '“Forms only, per doctor per month” = the price of a form × the visits from the plan, without recording. The whole visit is on the Costs and Money pages.',
  },
  'models.serviceFailures': {
    short: 'How many times a doctor got an error because of the service or Google.',
    template: 'How many times a doctor got an error because of the service or Google. Counted since {date}, when the server began recording errors.',
    long: 'The credit for a failed request is returned. Refusals (no credits, a limit) are not counted here — they are in the next tile.',
  },
  'models.refusals': {
    short: 'How many times the server itself said no: no credits, the daily limit, too many open conversations.',
    long: 'This is not a breakdown: this is how the payment rules and limits work.',
  },
  'models.proxies': {
    short: 'Indirect signs of trouble in the period.',
    long: 'These are not failures, only what we can see without an error log.',
  },
  'models.heatmap': {
    short: 'Forms by day of the week and hour (Vilnius time). Darker means more.',
    long: 'The peaks are 8:00 and 16:00–17:00. Google’s delays are felt most in these hours, and the peak will be there as we grow. For now it is mostly one doctor.',
  },
  'models.risks': {
    short: 'What may break or cost more, and when. The most urgent is at the top.',
  },
  'models.preview': {
    short: 'Trial version of a model: Google may remove it at short notice.',
  },
  'models.eu': {
    short: 'Servers in the EU: the data is processed only in the EU. This matters for GDPR, the EU data protection law.',
    long: 'The current main model has no EU servers anywhere at Google.',
  },
};
