// Copy of the Money page (§4.2, OVERRIDES O1: plain English). Every key starts with 'money.'.
// COPY = labels, answers, empty states, table headers, section lines; DEFS = { short, long?, template? }
// for the (i) hints (hintKey 'money.<key>'). Placeholders are filled with already formatted text.

export const COPY = {
  'money.title': 'Money',
  'money.question': 'How much money comes in, how much we keep, and will it pay off at 100–300 doctors?',

  // --- The period inside a sentence ("Result in the last 30 days: …") -----------------------------------
  'money.period.last7': 'in the last 7 days',
  'money.period.last30': 'in the last 30 days',
  'money.period.month': 'in {month}',
  'money.period.monthSoFar': 'in {month} so far',
  'money.period.year': 'in {year}',
  'money.period.yearSoFar': 'in {year} so far',
  'money.period.allTime': 'since the start',
  'money.period.custom': 'in {range}',

  // --- Answer -----------------------------------------------------------------------------------------
  'money.answer.revenueOff':
    'Stripe is not connected to the stats, so income is not visible. Judging by credit balances, doctors made at most {n} purchases for {sum} in all (indirect).',
  'money.answer.revenueOffNone': 'Stripe is not connected to the stats, so income is not visible. Costs {period}: {cost}.',
  'money.answer.revenueError': "Stripe didn't answer, so income is not visible right now. Costs {period}: {cost}.",
  'money.answer.revenueTest': 'Stripe is connected in test mode, so payments do not count as income. Costs {period}: {cost}.',
  'money.answer.noPayments': 'No payments {period}.',
  'money.answer.noPaymentsLast': 'No payments {period}. The last purchase was on {date}.',
  'money.answer.result': 'Result {period}: {result} — income {net}, costs {cost}.',
  'money.answer.plan': 'Plan ({scenario}): at {s0} doctors about {r0} a month, at {s1} about {r1}; we keep {pct} of income.',
  'money.answer.planNoIncome': 'Plan ({scenario}): at {s0} doctors about {r0} a month, at {s1} about {r1}.',

  // --- Banners --------------------------------------------------------------------------------------
  'money.notCredited': 'A doctor paid, but the credits did not arrive: {n}. Add them by hand and check in Stripe: Developers → Webhooks.',
  'money.openStripe': 'Open Stripe',

  // --- Section chips ----------------------------------------------------------------------------------
  'money.nav.payments': 'Payments',
  'money.nav.credits': 'Credits',
  'money.nav.unit': 'One visit',
  'money.nav.scale': 'Scale',

  // --- A. Payments --------------------------------------------------------------------------------------
  'money.a.title': 'Payments',
  'money.a.headline': 'Doctors paid {gross} for {payments} purchases {period}.',
  'money.a.headline.one': 'Doctors paid {gross} for 1 purchase {period}.',
  'money.a.none': 'No payments {period}.',
  'money.a.off': 'Payments are not visible without Stripe.',
  'money.a.test': 'Stripe is in test mode, so its payments are not counted.',
  'money.tile.gross': 'Paid by doctors',
  'money.tile.gross.sub': '{n} purchases',
  'money.tile.gross.subOne': '1 purchase',
  'money.tile.gross.inferred': 'all time, at most {n} purchases',
  'money.tile.net': 'Income',
  'money.tile.net.sub': 'Stripe fee {fee}',
  'money.tile.net.subVat': 'Stripe fee and VAT {feeVat}',
  'money.tile.result': 'Result',
  'money.tile.result.sub': 'costs {cost}',
  'money.tile.margin': 'Kept, %',
  'money.tile.margin.noIncome': 'no income',
  'money.moneyChart.title': 'Income and costs',
  'money.moneyChart.none': 'No payments {period}. Costs were {cost} — see them day by day on the Costs page.',
  'money.moneyChart.noIncome': 'Income is not visible without Stripe. Costs were {cost} {period} — see them day by day on the Costs page.',
  'money.moneyChart.toCosts': 'Open Costs',
  'money.part.form': 'Forms',
  'money.part.recording': 'Recording',
  'money.part.anamnesis': 'Medical history',
  'money.part.fixed': 'Server',
  'money.col.bucket': 'Period',
  'money.payments.title': 'Purchases',
  'money.col.date': 'Date',
  'money.col.doctor': 'Doctor',
  'money.col.pack': 'Pack',
  'money.col.paid': 'Paid',
  'money.col.discount': 'Discount',
  'money.col.fee': 'Fee',
  'money.col.vat': 'VAT',
  'money.col.income': 'Income',
  'money.col.method': 'Paid with',
  'money.col.refund': 'Refund',
  'money.col.credited': 'Credits arrived',
  'money.pack': 'Pack {n}',
  'money.pack.unknown': 'Unknown pack',
  'money.method.card': 'Card',
  'money.method.link': 'Card (Link)',
  'money.method.revolut_pay': 'Revolut Pay',
  'money.method.paypal': 'PayPal',
  'money.method.other': 'Other',
  'money.credited.yes': '✓ arrived',
  'money.credited.no': '✗ did not arrive',
  'money.credited.pending': 'waiting for Stripe',
  'money.credited.unknown': 'older than 30 days — cannot check',
  'money.payments.empty': 'No purchases in this period.',
  'money.payments.emptyLast': 'No purchases in this period. The last one was on {date}.',
  'money.payments.off': 'Stripe is not connected. Judging by credit balances, there were at most {n} purchases in all time, up to {sum} (indirect).',
  'money.payments.offNone': 'Stripe is not connected, so purchases are not visible.',
  'money.payments.test': 'Stripe is in test mode: test payments are not listed.',
  'money.payments.total': 'Total',
  'money.otherStripeFees': 'Other Stripe fees in this period: {x}. These are fees of the whole Stripe account; they are not taken from Dr.Filler income.',
  'money.packs.title': 'Packs',
  'money.packs.toggle': 'Show the packs',
  'money.col.credits': 'Credits',
  'money.col.price': 'Price',
  'money.col.feeCard': 'Fee (EU card)',
  'money.col.netPack': 'Income per pack',
  'money.col.perCredit': 'Per credit',
  'money.col.bought': 'Bought',
  'money.col.boughtEur': 'Paid in period',

  // --- B. Credits -------------------------------------------------------------------------------------------
  'money.b.title': 'Credits',
  'money.b.headline': 'Doctors spent {spent} {period} and bought {sold}.',
  'money.b.headlineNoSold': 'Doctors spent {spent} {period}.',
  'money.tile.creditsSpent': 'Credits spent',
  'money.tile.creditsSpent.sub': 'for recording: {n}',
  'money.tile.creditsSold': 'Credits bought',
  'money.tile.balances': 'On balances',
  'money.tile.balances.sub': 'as of today',
  'money.tile.freeExposure': 'Free credits would cost us',
  'money.tile.freeExposure.sub': '{n} nobody paid for',
  'money.tile.freeExposure.none': 'no free credits on balances',
  'money.creditsByFeature.title': 'Credits spent: forms, recording, medical history',
  'money.feature.form': 'Forms',
  'money.feature.recording': 'Recording',
  'money.feature.anamnesis': 'Medical history',
  'money.note.beforeMeter':
    'Recording is paid by the minute since 23 Sep 2026. Before that, the first dictation after a form was free and a second one in a row cost 1 credit; those credits are counted from the log (estimate).',
  'money.balancesByClass.title': 'Credits on balances: who holds them',
  'money.class.paid': 'Bought',
  'money.class.gifted': 'Given by hand',
  'money.class.free': 'Welcome 15',
  'money.class.internal': 'My and test',
  'money.class.other': 'Other',

  // --- C. One credit and one visit ------------------------------------------------------------------------
  'money.c.title': 'One credit and one visit',
  'money.c.headline': 'From each form we keep {formLeft} ({formPct}); from 10 minutes of conversation, {liveLeft} ({livePct}).',
  'money.c.headlineLiveLoss': 'From each form we keep {formLeft} ({formPct}); 10 minutes of conversation lose {liveLoss}.',
  'money.packSwitch': 'Pack',
  'money.packOption.plan': 'As planned',
  'money.packOption.pack250': '250',
  'money.packOption.pack600': '600',
  'money.packOption.pack1500': '1500',
  'money.anatomy.title': 'What the price of one credit is made of',
  'money.anatomy.form': 'Form',
  'money.anatomy.live10': '10 minutes of conversation',
  'money.anatomy.dictation10': '10 minutes of dictation',
  'money.anatomy.anamnesis1': 'Medical history (1 credit)',
  'money.anatomy.vatFee': 'VAT and fee',
  'money.anatomy.fee': 'Stripe fee',
  'money.anatomy.cost': 'Costs',
  'money.anatomy.left': 'We keep',
  'money.anatomy.minus': 'minus {x}',
  'money.anatomy.minusLine': 'Costs {cost} — more than the {price} a credit brings.',
  'money.anatomy.perCredit': '{price} per credit',
  'money.anatomy.table': 'Show all four as a table',
  'money.col.creditPrice': 'Credit price',
  'money.col.cost': 'Costs',
  'money.col.kept': 'Kept',
  'money.visitTypes.title': 'A whole visit',
  'money.visit.typed': 'Typing only',
  'money.visit.dictation1': 'Dictation 1 min',
  'money.visit.live15': 'Conversation 15 min',
  'money.visit.live25': 'Conversation 25 min',
  'money.visit.measured': 'Average visit in this period (actual)',
  'money.col.visit': 'Visit',
  'money.col.doctorPays': 'Doctor pays',
  'money.doctorPays': '{credits} ≈ {range}',
  'money.kept': '{left} ({pct})',
  'money.safeFree': 'Even if {x} of visits were free, we would stay in the plus.',
  'money.safeFree.none': 'Even with no free visits, a visit costs more than it brings.',
  'money.visitTypes.worst': 'On the cheapest pack with VAT, a 15-minute conversation leaves {x}.',

  // --- D. Scale -------------------------------------------------------------------------------------------
  'money.d.title': 'Will it pay off at scale?',
  'money.scenarioSwitch': 'Scenario',
  'money.scenarioOption.plan': 'My plan',
  'money.scenarioOption.measured': 'As now',
  'money.scenarioOption.typed': 'Typing only',
  'money.scenarioOption.dictation1': 'Dictation 1 min',
  'money.scenarioOption.live15': 'Conversation 15 min',
  'money.scenarioOption.live25': 'Conversation 25 min',
  'money.scaleTable.title': 'At scale: will it pay off?',
  'money.scaleSteps.toggle': 'Show the math step by step (13 rows)',
  'money.step.visits': 'Visits',
  'money.step.creditsSpent': 'Credits spent',
  'money.step.grossEur': 'Paid by doctors',
  'money.step.vatEur': '− VAT',
  'money.step.feeEur': '− Stripe fee',
  'money.step.netEur': '= Income',
  'money.step.costGeminiFormsEur': 'Gemini: forms',
  'money.step.costSonioxEur': 'Soniox: recording',
  'money.step.costOpenaiEur': 'OpenAI: backup transcription',
  'money.step.costAnamnesisEur': 'Medical history',
  'money.step.costFixedEur': 'Server and other',
  'money.step.resultEur': '= Result',
  'money.step.marginPct': 'Kept, %',
  'money.col.step': 'Step',
  'money.col.nowTotal': 'Period, not converted',
  'money.sensitivity.title': 'What moves the result most',
  'money.sensitivity.row': 'If {change}: result {diff} a month.',
  'money.sensitivity.change.pack600': 'doctors buy pack 600 instead of 1500',
  'money.sensitivity.change.model38in2027': 'the main model is Gemini 3.8 Flash at its 2027 price',
  'money.sensitivity.change.vat': 'the company pays VAT',
  'money.sensitivity.change.live25': 'conversations last 25 minutes instead of 15',
  'money.sensitivity.change.free10': 'there is 10 percentage points more free work',
  'money.sensitivity.change.paypal': 'everyone pays with PayPal',
  'money.sensitivity.none': 'No single assumption moves the result by more than 50 cents a month.',
  'money.sensitivity.table': 'Show all assumptions',
  'money.col.assumption': 'Assumption',
  'money.col.resultMonth': 'Result per month',
  'money.col.diff': 'Difference',
  'money.capacity.title': 'Where we hit a limit',
  'money.capacity.soniox':
    'At {n} doctors, up to {value} conversations would run at once in the busiest hour, and the limit is {limit}. Ask Soniox to raise the limit in advance.',
  'money.capacity.firestore': 'At {n} doctors: about {value} database writes a day — above the free {limit}, about {eur} a month.',
  'money.capacity.dashboard':
    'At {n} doctors the stats history reaches 150,000 rows in about {months} months — then the stats will need daily summaries.',
  'money.capacity.dashboardSoon': 'At {n} doctors the stats history reaches 150,000 rows within a month — then the stats will need daily summaries.',
  'money.capacity.none': 'At {n} doctors, vendor limits are not in the way.',
  'money.capacity.label.soniox': 'Soniox: conversations at once',
  'money.capacity.label.firestore': 'Database writes a day',
  'money.capacity.label.dashboard': 'Stats history, rows',

  // --- Data notes ---------------------------------------------------------------------------------------
  'money.note.disputes': 'Disputed payments took {x} off income on the day of the dispute.',
  'money.note.feeEstimated': 'Some fees come from the price list (PayPal’s own fee, or a payment without a Stripe fee record), so income is an estimate.',
  'money.note.ignored': 'The same Stripe account has {n} other sales; they are not counted.',
  'money.note.fewRecordings': 'The average visit needs at least 20 recordings in the period; there were {n}.',
};

export const DEFS = {
  'money.gross': {
    short: 'How much doctors paid for credit packs, by payment date.',
    long: 'This is money before the Stripe fee and taxes. Promo code discounts are already taken off. Doctors pay in advance and spend the credits later, so payments and costs do not line up in time.',
  },
  'money.grossInferred': {
    short: 'Without Stripe we guess purchases from credit balances: the fewest packs that add up to each balance.',
    long: 'This is an upper limit for all time, not for the period. When Stripe is connected, the real payments replace it.',
  },
  'money.net': {
    short: 'Paid by doctors minus the Stripe fee, refunds and VAT (if the company pays it).',
    long: 'The fee comes from the Stripe payment itself. For PayPal, Stripe does not know PayPal’s own fee — we add it from the price list (estimate). VAT is the tax a VAT payer hands to the state: 21/121 of the pack price. Disputed payments are taken off on the day of the dispute.',
  },
  'money.result': {
    short: 'Income minus costs for the period.',
    long: 'Costs are the models, recording and our share of the server, at the vendors’ list prices. Income is counted by payment date.',
  },
  'money.margin': {
    short: 'The part of income we keep after all costs.',
    long: 'We count (income − costs) ÷ income. This is not a markup. With no income it cannot be counted, so we show “—”.',
  },
  'money.moneyChart': {
    short: 'Left: income, right: costs; the dot is the result of that stretch.',
    long: 'Income is counted by payment date, so a week with a pack purchase looks better than the weeks after it. What the costs are made of is in the tooltip and on the Costs page.',
  },
  'money.payments': {
    short: 'Every Stripe payment in the period.',
    long: 'We show only Dr.Filler pack purchases; other sales on the same Stripe account are not counted.',
  },
  'money.credited': {
    short: 'Whether the doctor got the credits after paying.',
    long: 'After a payment Stripe sends our server a message (a webhook), and that message adds the credits. We compare the payments in Stripe with the messages the server handled. Stripe keeps its message history for 30 days.',
  },
  'money.packs': {
    short: 'Pack price, what Stripe and VAT take, and what one credit leaves us.',
    long: 'The fee uses Stripe’s price for an EU card: 1.5% + €0.25. PayPal costs more: about 7% on the 250 pack.',
  },
  'money.creditsSpent': {
    short: 'Credits spent in the period: forms, recording, medical history.',
    long: 'A form is 1 credit. A medical history summary is what the log says was charged. Recording is 1 credit for every full 10 minutes, dictation and conversation together, leftovers carry over; this works since 23 Sep 2026. Until the server records the charges themselves, recording credits are counted from the minutes (estimate).',
  },
  'money.creditsSold': {
    short: 'How many credits doctors bought in the period.',
    long: 'From Stripe payments. While Stripe is not connected — “—”.',
  },
  'money.balances': {
    short: 'How many unspent credits doctors hold now.',
    long: 'This is the state as of today, so there is nothing to compare with. Most of it was added by hand, not bought.',
  },
  'money.freeExposure': {
    short: 'What the credits nobody paid for would cost us if they were spent.',
    long: 'We take the balances of everyone who did not buy (given by hand, welcome 15, my and test accounts). Two estimates: if all of it goes on forms, and if all of it goes on recorded conversations (10 minutes per credit). The truth is somewhere in between. Balances of paying doctors are left out, even though some of them also got credits by hand.',
  },
  'money.creditsByFeature': {
    short: 'What the spent credits went on.',
  },
  'money.balancesByClass': {
    short: 'Bought, given by hand, welcome 15, and my and test accounts.',
    long: 'The account type comes from Stripe payments; while Stripe is not connected, from the balance (indirect). “Purchase not found” — the balance looks like a purchase, but Stripe has no payment for it.',
  },
  'money.anatomy': {
    short: 'Where the price of one credit goes: taxes and fees, our costs, and what we keep.',
    long: 'The bar is the price of 1 credit in the chosen pack. Grey is VAT and the Stripe fee, dark is our costs to vendors, blue is what we keep. If the costs are bigger than the credit price, the bar turns red.',
  },
  'money.visitTypes': {
    short: 'A form plus recording: what the doctor pays, what it costs us and what we keep.',
    long: 'Credits: 1 for the form and 1 for every 10 minutes of recording (on average, with leftovers carried over). Prices are from the last 30 days with the current model setup. The last row is the average visit of the chosen period, from real data.',
  },
  'money.safeFree': {
    short: 'What share of visits could be free while we stay in the plus.',
    long: 'We count 1 − cost of a visit ÷ income from a visit. For a form on the 1500 pack that is about three quarters.',
  },
  'money.scaleTable': {
    short: 'Now next to the plan, all per month.',
    template: 'Now next to the plan: one visit, one doctor, {s0} and {s1} doctors — all per month.',
    long: '“Now” is the real numbers of the period, converted to one month. The plan uses prices from the last 30 days (current model setup) times the amount of work from Settings. It is a “what if” calculation, not a promise.',
  },
  'money.scaleTable.income': {
    short: 'Now: payments by payment date. In the plan: credits spent × credit price.',
    long: 'So a month with work but no purchases looks worse “now” than in the plan.',
  },
  'money.sensitivity': {
    short: 'How much the monthly result moves if one assumption changes.',
    template: 'How much the monthly result at {n} doctors moves if one assumption changes.',
    long: 'Everything else stays as in the plan. This shows what to watch first.',
  },
  'money.capacity': {
    short: 'Vendor limits at this many doctors. Only the ones we would hit are shown.',
    long: 'Soniox: how many conversations run at once in the busiest hour (counted with room to spare: in 19 of 20 such hours it is not more). The limit of 10 can be raised by asking Soniox. Database (Firestore): about 5 writes per visit; above 20,000 a day it costs about $0.10 per 100,000. Stats history: about 3 rows per visit; after 150,000 rows the stats need daily summaries.',
  },
};
