// Copy of the Settings page (§4.9, OVERRIDES O1/O3/O4: plain English, no pseudonym warning, VAT off by
// default). Every key starts with 'settings.'. COPY = labels, answers, states, table headers; DEFS =
// { short, long?, template? } for the (i) hints (hintKey 'settings.<key>').

export const COPY = {
  'settings.title': 'Settings',
  'settings.question': 'How we count: VAT, my and test accounts, forecast assumptions, prices and data sources.',
  'settings.scopeLine': 'Measured values: last 30 days ({range}) · {scopeText}',

  // Answer (1–3 sentences)
  'settings.answer.plan': 'Forecasts assume {visits} visits per doctor a month ({scenario}), {pack}, {vat}.',
  'settings.answer.internalOne': 'One account is marked as mine or test; the switch “Without my and test accounts” hides it.',
  'settings.answer.internalMany': '{n} accounts are marked as mine or test; the switch “Without my and test accounts” hides them.',
  'settings.answer.noInternal': 'No account is marked as mine or test yet, so every average includes your own work.',
  'settings.answer.suggest': '{name} made {share} of all forms. If this is your account, tick it below under “My and test accounts”.',
  'settings.answer.sourcesOk': 'All {n} data sources work.',
  'settings.answer.sourcesBad': '{n} of {total} data sources need attention: {names}.',

  // Section chips
  'settings.nav.calc': 'How we count',
  'settings.nav.doctors': 'My and test accounts',
  'settings.nav.planning': 'Forecast',
  'settings.nav.prices': 'Prices',
  'settings.nav.eras': 'History',
  'settings.nav.sources': 'Data sources',
  'settings.nav.access': 'Access',
  'settings.nav.links': 'Links',

  // Saving (every section)
  'settings.saving': 'Saving…',
  'settings.saved': 'Saved. The numbers are recalculated.',
  'settings.saveFailedTitle': 'Not saved',
  'settings.saveFailed': '{reason} Your changes are still in the form — try again.',
  'settings.reason.network': 'There is no connection to the server.',
  'settings.reason.timeout': 'The server took too long to answer.',
  'settings.reason.auth': 'The key was refused.',
  'settings.reason.invalid': 'The server says one of the numbers is outside the allowed range.',
  'settings.reason.server': 'The server answered with an error.',
  'settings.readOnly': 'Saved settings could not be loaded, so saving is off: it would replace them with the defaults. Press ⟳ at the top.',

  // 1. How we count
  'settings.calc.title': 'How we count',
  'settings.vat.label': 'VAT',
  'settings.vat.off': "We don't pay VAT",
  'settings.vat.on': 'We pay 21% VAT',
  'settings.lang.label': 'Language',
  'settings.lang.en': 'English',
  'settings.lang.only': 'Only English for now.',

  // 2. My and test accounts
  'settings.internal.title': 'My and test accounts',
  'settings.internal.switch': 'In the numbers',
  'settings.internal.switchOff': 'Tick an account above first; then this switch can hide it from the numbers.',
  'settings.internal.probably': 'probably yours',
  'settings.internal.markAria': 'Mark {name} as mine or test',
  'settings.internal.phoneLine': 'All time: {forms} forms, costs {cost}',
  'settings.col.doctor': 'Doctor',
  'settings.col.forms': 'Forms, all time',
  'settings.col.cost': 'Costs, all time',
  'settings.col.mine': 'Mine / test',
  'settings.email.list': 'Doctor emails: shown in tables.',
  'settings.email.click': 'Doctor emails: shown one at a time, on a button.',
  'settings.email.off': 'Doctor emails: hidden.',
  'settings.email.how': 'To change this, set ADMIN_EMAIL_MODE in Railway: off — hidden, click — on a button, list — in tables.',

  // 3. Forecast assumptions
  'settings.planning.title': 'Forecast assumptions',
  'settings.planning.intro': 'This is a forecast: prices come from real data of the last 30 days, the amount of work comes from here.',
  'settings.group.main': 'Main',
  'settings.group.fine': 'Fine-tuning',
  'settings.field.visitsPerDoctorMonth': 'Visits per doctor a month',
  'settings.field.doctorScales': 'Scale, doctors',
  'settings.field.scale0': 'First scale, doctors',
  'settings.field.scale1': 'Second scale, doctors',
  'settings.field.howDoctorsWork': 'How doctors work',
  'settings.field.howDoctorsWork.custom': 'Your own mix — see Fine-tuning.',
  'settings.field.packMix': 'Which packs doctors buy, %',
  'settings.field.pack250': 'Pack 250, %',
  'settings.field.pack600': 'Pack 600, %',
  'settings.field.pack1500': 'Pack 1500, %',
  'settings.field.vat': 'VAT',
  'settings.field.vatLink': 'Change under “How we count”',
  'settings.field.liveShareOfVisits': 'Share of visits with a recorded conversation, %',
  'settings.field.liveMinutesPerVisit': 'Minutes of conversation per visit',
  'settings.field.dictationMinutesPerVisit': 'Minutes of dictation per visit without a conversation',
  'settings.field.conversationTokensPerMinute': 'Text a minute of conversation adds to the form, tokens',
  'settings.field.formCostBasis': 'Price of a form',
  'settings.formCost.measured': 'as in the last 30 days',
  'settings.formCost.assumed': 'by assumption',
  'settings.field.assumedIn': 'Form size by assumption: request, tokens',
  'settings.field.assumedOut': 'Form size by assumption: answer, tokens',
  'settings.field.anamnesisRunsPerDoctorMonth': 'Medical history summaries per doctor a month',
  'settings.field.paymentMethod': 'How doctors pay',
  'settings.method.card_eea_standard': 'Card from the EU (standard)',
  'settings.method.card_eea_premium': 'Card from the EU (premium)',
  'settings.method.card_international': 'Card from outside the EU',
  'settings.method.revolut_pay': 'Revolut Pay',
  'settings.method.paypal': 'PayPal',
  'settings.field.freeShare': 'Share of free work in the forecast, %',
  'settings.field.railway': 'Railway — Dr.Filler’s share, $ a month',
  'settings.field.other': 'Other fixed costs, $ a month',
  'settings.field.workdaysPerMonth': 'Working days in a month',
  'settings.field.peakHourShare': 'Share of a day’s visits in the busiest hour, %',
  'settings.field.sonioxStreamLimit': 'Soniox limit, conversations at once',
  'settings.measured': 'measured: {value}',
  'settings.measured.none': 'not measured yet',
  'settings.measured.packMix': 'measured: {p250} / {p600} / {p1500} of credits, from {n} payments',
  'settings.measured.method': 'measured: mostly {method}, from {n} payments',
  'settings.measured.server': 'server setting: {value}',
  'settings.measured.openai': 'backup OpenAI took {share} of dictations',
  'settings.rawMethod.card': 'card',
  'settings.rawMethod.link': 'card',
  'settings.rawMethod.revolut_pay': 'Revolut Pay',
  'settings.rawMethod.paypal': 'PayPal',
  'settings.rawMethod.other': 'another way',
  'settings.effect.conversation': '≈ +{cents} to a visit with a conversation',
  'settings.effect.form': '≈ {cents} per form',
  'settings.effect.usd': '≈ {eur} a month',
  'settings.hint.railway': 'server + stats ≈ 29% of the whole Railway bill',
  'settings.packs.sum': 'Together: {sum}',
  'settings.resetField': 'Back to the default: {value}',
  'settings.save': 'Save',
  'settings.resetAll': 'Reset to defaults',
  'settings.resetAll.done': 'Defaults are in the form. Press Save to use them.',
  'settings.unsaved': 'Not saved yet.',
  'settings.error.number': 'Enter a number.',
  'settings.error.range': 'Enter a number from {min} to {max}.',
  'settings.error.packSum': 'The three packs must add up to 100% (now {sum}).',
  'settings.error.summary': 'Check the fields marked in red: {fields}.',

  // 4. Prices and exchange rate
  'settings.prices.title': 'Prices and exchange rate',
  'settings.prices.fx': '$1 = €{rate} (ECB, {date})',
  'settings.prices.checked': 'Prices checked on {date}',
  'settings.prices.fromServer': 'Price table: from the server',
  'settings.prices.builtIn': 'Price table: built-in copy from {date}',
  'settings.prices.link': 'All prices',

  // 5. Setup history
  'settings.eras.title': 'Setup history',
  'settings.eras.now': 'Now forms are written by {main}, {where}; backup: {fallback}. Dictation: {dictation}. {billing}',
  'settings.eras.noFallback': 'none',
  'settings.eras.show': 'Show the whole history',
  'settings.eras.hide': 'Hide the history',
  'settings.eras.still': 'now',
  'settings.col.from': 'From',
  'settings.col.to': 'To',
  'settings.col.what': 'What',
  'settings.col.note': 'Note',
  'settings.era.model': 'Forms: {main}, {where}',
  'settings.era.modelFallback': 'Forms: {main}, {where}; backup {fallback}',
  'settings.era.transcription': 'Dictation: {main}',
  'settings.era.transcriptionFallback': 'Dictation: {main}; backup {fallback}',
  'settings.era.billing.per-visit': 'Payment: 1 credit per form; a second recording in a row costs 1 credit',
  'settings.era.billing.audio-meter': 'Payment: 1 credit per form + 1 credit per 10 minutes of recording',
  'settings.billingNow.per-visit': 'Recording is paid per visit.',
  'settings.billingNow.audio-meter': 'Recording is paid by the minute: 1 credit per 10 minutes.',
  'settings.eraNote.test': 'a 6-minute test',
  'settings.eraNote.vertexEu': 'trial on Google Cloud, EU only',
  'settings.eraNote.testDay': 'test day: several models',
  'settings.eraNote.timeout': 'the backup answers after {sec} s',

  // 6. Data sources
  'settings.sources.title': 'Data sources',
  'settings.source.usage': 'Request log',
  'settings.source.doctors': 'Doctors',
  'settings.source.config': 'Server settings',
  'settings.source.revenue': 'Stripe',
  'settings.source.soniox': 'Soniox',
  'settings.source.costs': 'Invoices by month',
  'settings.source.settings': 'Dashboard settings',
  'settings.state.ok': 'works',
  'settings.state.off': 'off',
  'settings.state.error': 'error',
  'settings.state.limited': 'limited',
  'settings.state.test': 'test mode',
  'settings.col.source': 'Source',
  'settings.col.state': 'State',
  'settings.col.updated': 'Data from',
  'settings.col.rows': 'Records',
  'settings.sourceNote.limited': 'only the last 90 days',
  'settings.sourceNote.static': 'using the built-in price table',
  'settings.sourceNote.defaults': 'using the defaults',
  'settings.sourceNote.test': 'payments do not count as income',
  'settings.sourceNote.no_stripe_key': 'no Stripe key on the server',
  'settings.sourceNote.stripe_error': 'Stripe answered with an error',
  'settings.sourceNote.stripe_timeout': 'Stripe did not answer in time',
  'settings.sourceNote.no_soniox_key': 'no Soniox key on the server',
  'settings.sourceNote.soniox_error': 'Soniox answered with an error',
  'settings.sources.details': 'Show the details',
  'settings.sources.start': 'The log starts on {date}.',
  'settings.sources.v2Since': 'New log fields since {date}.',
  'settings.sources.v2None': 'New log fields: not yet.',
  'settings.load':
    'The history has {rows} rows; one load of the dashboard reads all of them (every 10 minutes while it is open). With {s0} doctors ≈ {perMonth} rows a month will be added, and in about {months} months the dashboard will need daily totals.',
  'settings.load.noGrowth': 'The history has {rows} rows; one load of the dashboard reads all of them (every 10 minutes while it is open).',
  'settings.quality.title': 'Data quality',
  'settings.quality.droppedBeforeOrigin': 'Rows from before the log start (skipped)',
  'settings.quality.duplicateIds': 'Duplicate rows (skipped)',
  'settings.quality.unknownModels': 'Models missing from the price table (priced as Gemini 3.5 Flash)',
  'settings.quality.openaiRowsNoLength': 'OpenAI dictations without a length (minutes worked out from the file size)',
  'settings.quality.derivedThinkingRows': 'Forms whose thinking tokens were worked out',
  'settings.quality.zeroByteDictations': 'Empty dictation files',

  // 7. Access
  'settings.access.title': 'Access',
  'settings.access.remembered': 'The key is remembered on this device.',
  'settings.access.session': 'The key is kept only until this tab is closed.',
  'settings.access.demo': 'Demo data: no key is used.',
  'settings.access.change': 'Change key',

  // 8. Links
  'settings.links.title': 'Links',
  'settings.link.stripePayments': 'Stripe — payments',
  'settings.link.stripeNotices': 'Stripe — payment notices to our server',
  'settings.link.soniox': 'Soniox console',
  'settings.link.aiStudio': 'Google AI Studio — prepaid balance',
  'settings.link.gcpBilling': 'Google Cloud Billing',
  'settings.link.railway': 'Railway',

  // Notes
  'settings.note.topDoctor': 'Measured values mostly describe one doctor: {share} of the forms in the last 30 days are theirs.',
  'settings.note.fewConversations': 'We measure conversation length once there are 20 conversations; so far there are {n}, so the plan value is used.',
  'settings.note.convAssumed': 'The text a conversation adds to a form stays an assumption until 20 forms arrive with conversation text.',
};

export const DEFS = {
  'settings.vat': {
    short: 'Whether the company pays VAT. It changes income only.',
    long: 'VAT is the tax a VAT payer hands to the state from every sale: 21/121 of the pack price. For a €12.50 pack that is €2.17. The company does not pay VAT now.',
  },
  'settings.lang': { short: 'The language of the whole dashboard.' },
  'settings.internal': {
    short: 'Your own and test accounts. The switch “Without my and test accounts” hides them.',
    long: 'Only money and the amount of work are hidden. Speed and failures always count all traffic. Accounts marked on the server cannot be changed here.',
  },
  'settings.planning': {
    short: 'Assumptions for every forecast: one doctor and the two scales below.',
    long: 'Prices come from real data of the last 30 days (the current model setup); the amount of work comes from here. “Measured” is what the data of the last 30 days shows — often mostly one doctor.',
  },
  'settings.visitsPerDoctorMonth': {
    short: 'How many patients one doctor sees in a month.',
    long: 'Measured: forms per active doctor in the last 30 days, converted to a month. One very active doctor pulls it up.',
  },
  'settings.doctorScales': { short: 'The two numbers of doctors every forecast is shown for.' },
  'settings.howDoctorsWork': {
    short: 'A quick way to fill the three recording fields in Fine-tuning.',
    long: '“15 min conversation” means every visit has a recorded 15-minute conversation. “1 min dictation” means no conversation and one minute of dictation per visit.',
  },
  'settings.packMix': {
    short: 'Which packs doctors buy decides how much one credit brings in.',
    long: 'Enter the share of credits bought in each pack; together 100%. Measured: from all Stripe payments.',
  },
  'settings.vatField': { short: 'VAT changes only income. It is set under “How we count”.' },
  'settings.liveShareOfVisits': { short: 'How many visits have a recorded conversation.', long: 'Measured: live conversations ÷ forms in the last 30 days.' },
  'settings.liveMinutesPerVisit': { short: 'How long a recorded conversation lasts.', long: 'Measured once there are 20 conversations in the last 30 days.' },
  'settings.dictationMinutesPerVisit': {
    short: 'Minutes of dictation in a visit without a conversation.',
    long: 'Measured: all dictation minutes ÷ visits without a conversation, last 30 days. Old OpenAI minutes are worked out from the file size.',
  },
  'settings.conversationTokensPerMinute': {
    short: 'How much text one minute of recorded conversation adds to the form.',
    long: 'While there are few conversations this is an assumption: about 250 tokens a minute (133–367 by estimate). When 20 forms arrive with conversation text, we replace it with the measured value.',
  },
  'settings.formCostBasis': {
    short: 'Where the price of one form comes from.',
    long: '“As in the last 30 days” is the mean cost of forms with the current model setup (at least 20 forms). “By assumption” prices the form size below on the current main model.',
  },
  'settings.assumedFormTokens': {
    short: 'The size of one form when the price is “by assumption”.',
    long: 'A token is a small piece of text, about 3–4 letters. The request is what we send to the model, the answer is what it writes.',
  },
  'settings.anamnesisRunsPerDoctorMonth': {
    short: 'How often a doctor collects a medical history summary.',
    long: 'Measured: summaries per active doctor in the last 30 days, converted to a month. Summaries are grouped from single calls by time, so this is an estimate.',
  },
  'settings.paymentMethod': {
    short: 'Stripe takes a different fee for each way of paying.',
    long: 'Measured: the way most Stripe payments were made. Stripe does not tell us whether a card is standard or premium.',
  },
  'settings.freeShare': {
    short: 'How much of the work in the forecast is done on free credits.',
    long: '0% means a forecast for paying doctors. Measured: the share of costs made by accounts that never paid — now almost all of it.',
  },
  'settings.railwayShare': {
    short: 'Dr.Filler’s share of the Railway bill.',
    long: 'Other projects run on the same Railway account. Dr.Filler (server and stats) is about 29% of the bill, about $1.96 a month with VAT.',
  },
  'settings.otherFixed': { short: 'Any other monthly bill, in dollars. It is added to every forecast.' },
  'settings.workdaysPerMonth': { short: 'Days doctors work in a month. Used to find the busiest hour.' },
  'settings.peakHourShare': {
    short: 'Which part of a day’s visits falls into the busiest hour.',
    long: 'Needed to estimate how many conversations run at the same time. Measured on weekdays of the last 30 days (at least 200 forms); now about 15%.',
  },
  'settings.sonioxStreamLimit': {
    short: 'How many live conversations Soniox takes at once.',
    long: 'Ask Soniox to raise it before many doctors record at the same time.',
  },
  'settings.prices': { short: 'The price table and the exchange rate every cost on the dashboard uses.' },
  'settings.fx': {
    short: 'The rate for turning dollars into euros.',
    long: 'Vendors bill in dollars; Stripe pays out in euros. One ECB rate is used for the whole dashboard.',
  },
  'settings.eras': {
    short: 'Which model and which way of paying worked on which dates.',
    long: 'A change of setup explains jumps on the charts.',
  },
  'settings.sources': {
    short: 'Where the dashboard gets its data and whether it all works.',
    long: 'The log and the doctors are refreshed every 10 minutes. Stripe and Soniox too; if they do not answer, the rest of the dashboard still works.',
  },
  'settings.load': {
    short: 'How big the history is and when the dashboard will need daily totals.',
    long: 'Every load reads every row of the history. At about 150,000 rows one load becomes too big, and the server should start keeping daily totals instead.',
  },
  'settings.quality': { short: 'Rows the dashboard skipped or had to work out.' },
  'settings.access': { short: 'The admin key of this browser.' },
  'settings.links': { short: 'Where the real bills and settings live.' },
};
